In [1]:
import pandas as pd

df = pd.read_csv("../data/data_for_model.csv")

df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91
1,4,82,No,4,2,65
2,8,51,Yes,7,2,45
3,5,52,Yes,5,2,36
4,7,75,No,8,5,66

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     499 non-null    int64
 1   Previous Scores                   499 non-null    int64
 2   Extracurricular Activities        499 non-null    str
 3   Sleep Hours                       499 non-null    int64
 4   Sample Question Papers Practiced  499 non-null    int64
 5   Performance Index                 499 non-null    int64
dtypes: int64(5), str(1)
memory usage: 23.5 KB

In [3]:
df.columns

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='str')

In [4]:
df.describe()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
count,499.000000,499.000000,499.000000,499.000000,499.000000
mean,4.903808,69.659319,6.420842,4.454910,55.058116
std,2.614212,17.430878,1.689575,2.842497,19.862849
min,1.000000,40.000000,4.000000,0.000000,10.000000
25%,3.000000,55.000000,5.000000,2.000000,39.500000
50%,5.000000,70.000000,6.000000,4.000000,56.000000
75%,7.000000,85.000000,8.000000,7.000000,71.000000
max,9.000000,99.000000,9.000000,9.000000,100.000000

In [5]:
df["Extracurricular Activities"] = df["Extracurricular Activities"].map({
    "Yes": 1,
    "No": 0
})

In [6]:
X = df.drop("Performance Index", axis=1)
y = df["Performance Index"]

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [8]:
from sklearn.linear_model import LinearRegression

model1 = LinearRegression()
model1.fit(X_train, y_train)

y_pred1 = model1.predict(X_test)

In [9]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

r2_1 = r2_score(y_test, y_pred1)

n = X_test.shape[0]
p = X_test.shape[1]
adjusted_r2_1 = 1 - ((1 - r2_1) * (n - 1) / (n - p - 1))

mae_1 = mean_absolute_error(y_test, y_pred1)
mse_1 = mean_squared_error(y_test, y_pred1)
rmse_1 = np.sqrt(mse_1)

print("R²:", r2_1)
print("Adjusted R²:", adjusted_r2_1)
print("MAE:", mae_1)
print("MSE:", mse_1)
print("RMSE:", rmse_1)

R²: 0.9889247731075976
Adjusted R²: 0.9883356652941719
MAE: 1.5809100502333666
MSE: 4.321602264413723
RMSE: 2.0788463782621656

In [10]:
print("Intercept:", model1.intercept_)

for feature, coefficient in zip(X.columns, model1.coef_):
    print(feature, ":", coefficient)

Intercept: -34.04242357695019
Hours Studied : 2.8827219785302614
Previous Scores : 1.018818179954844
Extracurricular Activities : 0.6160527586560602
Sleep Hours : 0.4262630155190055
Sample Question Papers Practiced : 0.20726935875544067

In [11]:
X_poly = X.copy()
X_poly["Hours Studied Squared"] = X_poly["Hours Studied"] ** 2

X_train_poly, X_test_poly, y_train_poly, y_test_poly = train_test_split(
    X_poly, y, test_size=0.2, random_state=42
)

model2 = LinearRegression()
model2.fit(X_train_poly, y_train_poly)

y_pred2 = model2.predict(X_test_poly)

In [12]:
r2_2 = r2_score(y_test_poly, y_pred2)

n = X_test_poly.shape[0]
p = X_test_poly.shape[1]

adjusted_r2_2 = 1 - ((1 - r2_2) * (n - 1) / (n - p - 1))
mae_2 = mean_absolute_error(y_test_poly, y_pred2)
mse_2 = mean_squared_error(y_test_poly, y_pred2)
rmse_2 = np.sqrt(mean_squared_error(y_test_poly, y_pred2))

print("Polynomial Regression Results")
print("R²:", r2_2)
print("Adjusted R²:", adjusted_r2_2)
print("MAE:", mae_2)
print("MSE:", mse_2)
print("RMSE:", rmse_2)

Polynomial Regression Results
R²: 0.9887430538860871
Adjusted R²: 0.9880167992980927
MAE: 1.595607898180801
MSE: 4.392509904211705
RMSE: 2.0958315543506125

In [13]:
X_interaction = X.copy()
X_interaction["Hours × Previous Scores"] = (
    X_interaction["Hours Studied"] * X_interaction["Previous Scores"]
)

X_train_int, X_test_int, y_train_int, y_test_int = train_test_split(
    X_interaction, y, test_size=0.2, random_state=42
)

model3 = LinearRegression()
model3.fit(X_train_int, y_train_int)

y_pred3 = model3.predict(X_test_int)

In [14]:
r2_3 = r2_score(y_test_int, y_pred3)

n = X_test_int.shape[0]
p = X_test_int.shape[1]

adjusted_r2_3 = 1 - ((1 - r2_3) * (n - 1) / (n - p - 1))
mae_3 = mean_absolute_error(y_test_int, y_pred3)
mse_3 = mean_squared_error(y_test_int, y_pred3)
rmse_3 = np.sqrt(mean_squared_error(y_test_int, y_pred3))

print("Interaction Regression Results")
print("R²:", r2_3)
print("Adjusted R²:", adjusted_r2_3)
print("MAE:", mae_3)
print("MSE:", mse_3)
print("RMSE:", rmse_3)

Interaction Regression Results
R²: 0.9889073880019096
Adjusted R²: 0.988191735614936
MAE: 1.5845653834250861
MSE: 4.32838600914766
RMSE: 2.080477351270054

In [15]:
comparison = pd.DataFrame({
    "Model": [
        "Basic MLR",
        "MLR with Polynomial Term",
        "MLR with Interaction Term"
    ],
    "R²": [r2_1, r2_2, r2_3],
    "Adjusted R²": [adjusted_r2_1, adjusted_r2_2, adjusted_r2_3],
    "RMSE": [rmse_1, rmse_2, rmse_3]
})

comparison

                       Model        R²  Adjusted R²      RMSE
0                  Basic MLR  0.988925     0.988336  2.078846
1   MLR with Polynomial Term  0.988743     0.988017  2.095832
2  MLR with Interaction Term  0.988907     0.988192  2.080477

In [16]:
student = pd.DataFrame({
    "Hours Studied": [8],
    "Previous Scores": [85],
    "Extracurricular Activities": [1],
    "Sleep Hours": [7],
    "Sample Question Papers Practiced": [6]
})

student_poly = student.copy()
student_poly["Hours Studied Squared"] = student_poly["Hours Studied"] ** 2

student_interaction = student.copy()
student_interaction["Hours × Previous Scores"] = (
    student_interaction["Hours Studied"] *
    student_interaction["Previous Scores"]
)

prediction1 = model1.predict(student)[0]
prediction2 = model2.predict(student_poly)[0]
prediction3 = model3.predict(student_interaction)[0]

print("Basic MLR Prediction:", prediction1)
print("Polynomial Model Prediction:", prediction2)
print("Interaction Model Prediction:", prediction3)

Basic MLR Prediction: 80.46240756727536
Polynomial Model Prediction: 80.52312994995506
Interaction Model Prediction: 80.48624318875775

In [17]:
print("MODEL COMPARISON")
display(comparison) 

print("\nSTUDENT PREDICTIONS")
print(f"Basic MLR: {prediction1:.2f}")
print(f"Polynomial Model: {prediction2:.2f}")
print(f"Interaction Model: {prediction3:.2f}")

MODEL COMPARISON

                       Model        R²  Adjusted R²      RMSE
0                  Basic MLR  0.988925     0.988336  2.078846
1   MLR with Polynomial Term  0.988743     0.988017  2.095832
2  MLR with Interaction Term  0.988907     0.988192  2.080477

STUDENT PREDICTIONS
Basic MLR: 80.46
Polynomial Model: 80.52
Interaction Model: 80.49

In [18]:
print(comparison)
print("\nPredictions:")
print("Basic MLR:", prediction1)
print("Polynomial:", prediction2)
print("Interaction:", prediction3)

                       Model        R²  Adjusted R²      RMSE
0                  Basic MLR  0.988925     0.988336  2.078846
1   MLR with Polynomial Term  0.988743     0.988017  2.095832
2  MLR with Interaction Term  0.988907     0.988192  2.080477

Predictions:
Basic MLR: 80.46240756727536
Polynomial: 80.52312994995506
Interaction: 80.48624318875775

In [19]:
print("MAE:", mae_1)
print("MSE:", mse_1)

MAE: 1.5809100502333666
MSE: 4.321602264413723